import { Country } from '../../../../domain/enum/country';

export const userSeedData = [
    {
        userId: '1',
        phoneNumber: '123456789',
        email: 'johndoe@email.com',
        createdOn: 123456789,
        activePlan: 1,
        activePlanId: '1',
        subscription: 'active',
        recentSubscriptionDate: 123456789,
        recentSubscriptionExpires: 123456789,
        countryCode: Country.NIGERIA,
        countryDate: '2022-01-01',
        network: 'network',
        firstName: 'John',
        lastName: 'Doe',
        fullName: 'John Doe',
        providerSub: 'providerSub',
        billingAccount: {
            email: 'billingAccountEmail',
            fullName: 'billingAccountFullName',
        },
    },
    {
        userId: '2',
        phoneNumber: '987654321',
        email: 'adamwells@mail.com',
        createdOn: 987654321,
        activePlan: 2,
        activePlanId: '2',
        subscription: 'active',
        recentSubscriptionDate: 987654321,
        recentSubscriptionExpires: 987654321,
        countryCode: Country.GHANA,
        countryDate: '2023-01-01',
        network: 'network',
        firstName: 'Adam',
        lastName: 'Wells',
        fullName: 'Adam Wells',
    },
];
